### ISSUE TITLE
Cannot play music on Ubuntu

### ISSUE THREAD

**Issue by eggplants** [plaaosert/credits_public#5]
```shellsession
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

$ uname -vorm
5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 GNU/Linux

$ yt-dlp "https://soundcloud.com/frums/credits-ex" -x --audio-format wav -o media/credits.wav

$ python credits.py
[1;1Hskips

1 | start
2 | title
3 | funding
4 | loading
5 | break
6 | final
Traceback (most recent call last):
  File "/home/eggplants/prog/c/credits.py", line 314, in <module>
    if keyboard.is_pressed("1"):
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/keyboard/__init__.py", line 410, in is_pressed
    _listener.start_if_necessary()
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/eggplants/.pyenv/versions/3.10.4/lib/python3.10/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.

$ sudo su

# python3 credit.py
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
^[[1;1Hskips

1 | start
2 | title
3 | funding
4 | loading
5 | break
6 | final

(... music video was played without no sound ...)
```

**Comment by plaaosert** [comment]
This looks like a problem with the just_playback library. Try flagging up an issue there.
(sorry for such a late response!)

https://github.com/cheofusi/just_playback
